{% set name = "napari-matplotlib" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_matplotlib-{{ version }}.tar.gz
  sha256: 40f635cd2118f9c19bc596433d9bc401af8111ae7520af8206359ab7beb189e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - matplotlib-base
    - napari <0.4.18
    - numpy
    - python >=3.8
    - qtpy
    - tinycss2

test:
  imports:
    - napari_matplotlib
  commands:
    - python -c 'from napari_matplotlib import __version__;print(__version__)'
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/matplotlib/napari-matplotlib
  summary: A plugin to use Matplotlib with napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dstansby
    - goanpeca
    - jaimergp
