{% set name = "napari-matplotlib" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 104e6c63258a096114705693a2c15ceafb46083f273d45c10d6c3b59e2d07773

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - matplotlib-base
    - napari <0.5
    - numpy
    - python >=3.9
    - qtpy
    - tinycss2

test:
  imports:
    - napari_matplotlib
  commands:
    - python -c 'from napari_matplotlib import __version__;print(__version__)'
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/matplotlib/napari-matplotlib
  summary: A plugin to use Matplotlib with napari
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/matplotlib/napari-matplotlib

extra:
  recipe-maintainers:
    - dstansby
    - goanpeca
    - jaimergp
