{% set name = "napari-matplotlib" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_matplotlib-{{ version }}.tar.gz
  sha256: 0b755e29968401d2b964a46d81afb347ff40c26d120c0cbab4b2408b40776e7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - matplotlib-base
    - napari
    - numpy
    - python >=3.8

test:
  imports:
    - napari_matplotlib
  commands:
    - python -c 'from napari_matplotlib import __version__;print(__version__)'
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/matplotlib/napari-matplotlib
  summary: A plugin to use Matplotlib with napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dstansby
    - goanpeca
    - jaimergp
